version: '3.6'
services:
  frontend:
    image: tingliu09/vue-ocean-demo
    container_name: frontend-vue
    ports:
      - 80:80
    depends_on:
      - backend
    networks: 
      - backdb    

  backend:
    image: tingliu09/springboot-ocean-demo
    container_name: backend-springboot
    ports:
      - 8090:8090
    depends_on:
        database:
            condition: service_healthy
    networks:
      - backdb


  database:
    image: mysql:latest
    container_name: mysqlDB
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=oceandb
    volumes:
      - ./data:/var/lib/mysql
      - ./ocean.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backdb
    healthcheck:
        test: '/usr/bin/mysql --user=root --password=password --execute "SHOW DATABASES;"'
        interval: 10s
        timeout: 20s
        retries: 10

      
networks: 
  backdb:
    driver: bridge

